# Coin Price configuration

app:
  name: Coindicator for OSX
  description: Coindicator is a cryptocurrency price indicator applet for Mac OSX, and a direct port of Nil Gradisnik's Coin Price Indicator (https://github.com/bluppfisk/coinprice-indicator)
  url: https://github.com/bluppfisk/coindicator
  version: "0.1"

author:
  name: Sander Van de Moortel
  email: sander.vandemoortel@gmail.com
  copyright: Copyright (C) 2017 Sander Van de Moortel

artist:
  name: Alicen Maniscalco
  email: alicenfm@gmail.com
